apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: first-queue-cd-argo-1
spec:
  forProvider:
    name: first-queue-cd-argo-2
    region: us-east-1
  providerConfigRef:
    name: irsa-providerconfig
