apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: crossplane-queue-cd-argo-1
spec:
  forProvider:
    name: crossplane-queue-cd-argo-1
    region: us-east-1
  providerConfigRef:
    name: irsa-providerconfig
