apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
  name: crossplane-bucket-cd-argo-3
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: irsa-providerconfig

