apiVersion: kubernetes.crossplane.io/v1beta1
kind: Object
metadata:
  name: {{ .Values.global.name }}-object-aws-auth
  namespace: crossplane-system
spec:
  deletionPolicy: Orphan
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: aws-auth
        namespace: kube-system
      data:
        mapRoles: |
          {{- range .Values.awsAuth.mapRoles }}
          - rolearn: {{ .rolearn }}
            username: {{ .username }}
            groups:
            {{- range .groups }}
              - {{ . }}
            {{- end }}
          {{- end }}
          - rolearn: {{ .Values.awsAuth.clusterAdminRole }}
            username: admin-user
            groups:
              - system:masters
  providerConfigRef:
    name: {{ $.Values.global.providerConfigRefsecret }}