apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: object-aws-auth
  namespace: crossplane-system
spec:
  deletionPolicy: Orphan
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: aws-auth
        namespace: kube-system
      data:
        mapRoles: |
          {{- range .Values.awsAuth.mapRoles }}
          - rolearn: {{ .rolearn }}
            username: {{ .username }}
            groups:
              {{- range .groups }}
              - {{ . }}
              {{- end }}
          {{- end }}


  providerConfigRef:
    name: {{ $.Values.global.providerConfigRefsecret }}       


