---
# LaunchTemplate
apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: {{ .Values.global.name }}-launch-template
spec:
  forProvider:
    region: {{ .Values.global.region }}
    name: {{ .Values.global.name }}-launch-template
    defaultVersion: {{ .Values.launchTemplate.version }}
    instanceType: {{ index .Values.nodeGroup.instanceTypes 0 }}
    imageId: {{ .Values.nodeGroup.imageId }}
    {{- if .Values.nodeGroup.diskSize }}
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          - volumeSize: {{ .Values.nodeGroup.diskSize }}
            volumeType: gp3
            encrypted: "true"
    {{- end }}
    tags:
      Name: {{ .Values.global.name }}-launch-template
    tagSpecifications:
      - resourceType: instance
        tags:
          Name: {{ .Values.global.name }}-ng
          eks:nodegroup-name: {{ .Values.global.name }}-ng
          {{- range $key, $value := .Values.nodeGroup.instanceTags }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}      
    userData: {{ include "eks.userdata" . | b64enc }}
  providerConfigRef:
    name: {{ $.Values.global.providerConfigRef }}
