apiVersion: eks.aws.upbound.io/v1beta2
kind: NodeGroup
metadata:
  name: {{ .Values.global.name }}-ng
  labels:
    nodegroup: {{ .Values.global.name }}-ng
    
spec:
  forProvider:
    region: {{ .Values.global.region }}
    clusterName: {{ .Values.global.name }}
    nodeRoleArn: {{ .Values.nodeGroup.nodeRoleArn }}
    subnetIds:
      {{- range .Values.vpc.subnetIds }}
      - {{ . | quote }}
      {{- end }}
    {{- if .Values.nodeGroup.capacityType }}
    capacityType: {{ .Values.nodeGroup.capacityType }}
    {{- end }}
    launchTemplate:
      name: {{ .Values.global.name }}-launch-template
      version: "$Default" #""1" #"$Latest"  
    scalingConfig:
      desiredSize: {{ .Values.nodeGroup.scalingConfig.desiredSize }}
      maxSize: {{ .Values.nodeGroup.scalingConfig.maxSize }}
      minSize: {{ .Values.nodeGroup.scalingConfig.minSize }}
    {{- if .Values.nodeGroup.tags }}
    tags:
      name: {{ .Values.global.name }}-ng
      eks:nodegroup-name: {{ .Values.global.name }}-ng
      {{- toYaml .Values.nodeGroup.tags | nindent 6 }}
    {{- end }}
    {{- if .Values.nodeGroup.taints }}    
    version: {{ .Values.global.version | quote }}
    {{- end }}
  providerConfigRef:
    name: {{ $.Values.global.providerConfigRef }}
  references:
    - name: lt
      resource:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: LaunchTemplate
        name: {{ .Values.nodeGroup.name }}-launch-template
    - name: asg
      resource:
        apiVersion: autoscaling.aws.upbound.io/v1beta2
        kind: AutoscalingGroup
        name: {{ .Values.nodeGroup.name }}-asg        