apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.providerConfigHelm.namehelm }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: {{ .Values.providerConfigHelm.kubeconfigSecretNamehelm }}
      key: {{ .Values.providerConfigHelm.kubeconfigSecretKeyhelm }}