apiVersion: kubernetes.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.providerConfig.name }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: {{ .Values.providerConfig.kubeconfigSecretName }}
      key: {{ .Values.providerConfig.kubeconfigSecretKey }}