# ---
# # templates/security-groups.yaml
# apiVersion: ec2.aws.upbound.io/v1beta1
# kind: SecurityGroup
# metadata:
#   name: {{ .Values.global.name }}-sg-1
#   labels:
#     ekscrossplane.io/sg-name: {{ .Values.global.name }}-sg-1
#   annotations:
#     "helm.sh/hook": pre-install  

# spec:
#   forProvider:
#     region: {{ .Values.global.region }}
#     vpcId: {{ .Values.vpc.id }}
#     description: "Security Group 1 for EKS cluster {{ .Values.global.name }}"
#     tags:
#       Name: {{ .Values.global.name }}-sg-1
#   providerConfigRef:
#     name: {{ .Values.global.providerConfigRef | default "irsa-providerconfig" }}
# ---
# #### Regras de saída
# apiVersion: ec2.aws.upbound.io/v1beta1
# kind: SecurityGroupRule
# metadata:
#   name: {{ .Values.global.name }}-cluster-sg-egress
#   labels:
#     eks-cluster: {{ .Values.global.name }}
# spec:
#   forProvider:
#     region: {{ .Values.global.region }}
#     securityGroupIdSelector:
#       matchLabels:
#         ekscrossplane.io/sg-name: {{ .Values.global.name }}-sg-1 
#     type: "egress"
#     protocol: "-1"
#     fromPort: -1
#     toPort: -1
#     cidrBlocks:
#       - "0.0.0.0/0"
#     description: "Allow all outbound traffic"
#   providerConfigRef:
#     name: {{ .Values.global.providerConfigRef }}
# ---
# #### Regras de entrada
# apiVersion: ec2.aws.upbound.io/v1beta1
# kind: SecurityGroupRule
# metadata:
#   name: {{ .Values.global.name }}-cluster-sg-ingress-kubelet
#   labels:
#     eks-cluster: {{ .Values.global.name }}
# spec:
#   forProvider:
#     region: {{ .Values.global.region }}
#     securityGroupIdSelector:
#       matchLabels:
#         ekscrossplane.io/sg-name: {{ .Values.global.name }}-sg-1 
#     type: "ingress"
#     protocol: "tcp"
#     fromPort: 10250
#     toPort: 10250
#     cidrBlocks:
#       - {{ .Values.vpc.cidrBlock | default "10.0.0.0/16" }}
#     description: "Allow kubelet API"
#   providerConfigRef:
#     name: {{ .Values.global.providerConfigRef }}

#### Ingress Rule for HTTPS (Port 443) with Source Security Group
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: {{ .Values.global.name }}-cluster-sg-ingress-https
  labels:
    eks-cluster: {{ .Values.global.name }}
spec:
  forProvider:
    region: {{ .Values.global.region }}
    securityGroupIdSelector:
      matchLabels:
        ekscrossplane.io/sg-name: {{ .Values.global.name }}-sg-1 
    type: "ingress"
    protocol: "tcp"
    fromPort: 443
    toPort: 443
    {{- if kindIs "slice" .Values.vpc.sourceSecurityGroupId }}
    sourceSecurityGroupId: {{ index .Values.vpc.sourceSecurityGroupId 0 | quote }}
    {{- else }}
    sourceSecurityGroupId: {{ .Values.vpc.sourceSecurityGroupId | quote }}
    {{- end }}
    description: "Allow HTTPS traffic from specific security group"
  providerConfigRef:
    name: {{ .Values.global.providerConfigRef }}
